// <auto-generated />
using CoreWebApiJewelleryProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreWebApiJewelleryProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231019173745_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BilekliklerSetler", b =>
                {
                    b.Property<int>("BilekliklersBileklikId")
                        .HasColumnType("int");

                    b.Property<int>("SetlersSetId")
                        .HasColumnType("int");

                    b.HasKey("BilekliklersBileklikId", "SetlersSetId");

                    b.HasIndex("SetlersSetId");

                    b.ToTable("BilekliklerSetler");
                });

            modelBuilder.Entity("CoreWebApiJewelleryProject.Model.Bileklikler", b =>
                {
                    b.Property<int>("BileklikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BMadeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTaslari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BileklikAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Bucreti")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BileklikId");

                    b.ToTable("bilekliklers");
                });

            modelBuilder.Entity("CoreWebApiJewelleryProject.Model.Kolyeler", b =>
                {
                    b.Property<int>("KolyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KMadeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KTaslari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KolyeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kucreti")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KolyeId");

                    b.ToTable("kolyelers");
                });

            modelBuilder.Entity("CoreWebApiJewelleryProject.Model.Kupeler", b =>
                {
                    b.Property<int>("KupeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KupMadeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KupTaslari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KupeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kupucreti")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KupeId");

                    b.ToTable("kupelers");
                });

            modelBuilder.Entity("CoreWebApiJewelleryProject.Model.Setler", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SetAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetId");

                    b.ToTable("setlers");
                });

            modelBuilder.Entity("CoreWebApiJewelleryProject.Model.Yuzukler", b =>
                {
                    b.Property<int>("YuzukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YMadeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YTaslari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Yucreti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YuzukAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YuzukId");

                    b.ToTable("yuzuklers");
                });

            modelBuilder.Entity("KolyelerSetler", b =>
                {
                    b.Property<int>("KolyelersKolyeId")
                        .HasColumnType("int");

                    b.Property<int>("SetlersSetId")
                        .HasColumnType("int");

                    b.HasKey("KolyelersKolyeId", "SetlersSetId");

                    b.HasIndex("SetlersSetId");

                    b.ToTable("KolyelerSetler");
                });

            modelBuilder.Entity("KupelerSetler", b =>
                {
                    b.Property<int>("KupelersKupeId")
                        .HasColumnType("int");

                    b.Property<int>("SetlersSetId")
                        .HasColumnType("int");

                    b.HasKey("KupelersKupeId", "SetlersSetId");

                    b.HasIndex("SetlersSetId");

                    b.ToTable("KupelerSetler");
                });

            modelBuilder.Entity("SetlerYuzukler", b =>
                {
                    b.Property<int>("SetlersSetId")
                        .HasColumnType("int");

                    b.Property<int>("YuzuklersYuzukId")
                        .HasColumnType("int");

                    b.HasKey("SetlersSetId", "YuzuklersYuzukId");

                    b.HasIndex("YuzuklersYuzukId");

                    b.ToTable("SetlerYuzukler");
                });

            modelBuilder.Entity("BilekliklerSetler", b =>
                {
                    b.HasOne("CoreWebApiJewelleryProject.Model.Bileklikler", null)
                        .WithMany()
                        .HasForeignKey("BilekliklersBileklikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreWebApiJewelleryProject.Model.Setler", null)
                        .WithMany()
                        .HasForeignKey("SetlersSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KolyelerSetler", b =>
                {
                    b.HasOne("CoreWebApiJewelleryProject.Model.Kolyeler", null)
                        .WithMany()
                        .HasForeignKey("KolyelersKolyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreWebApiJewelleryProject.Model.Setler", null)
                        .WithMany()
                        .HasForeignKey("SetlersSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KupelerSetler", b =>
                {
                    b.HasOne("CoreWebApiJewelleryProject.Model.Kupeler", null)
                        .WithMany()
                        .HasForeignKey("KupelersKupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreWebApiJewelleryProject.Model.Setler", null)
                        .WithMany()
                        .HasForeignKey("SetlersSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SetlerYuzukler", b =>
                {
                    b.HasOne("CoreWebApiJewelleryProject.Model.Setler", null)
                        .WithMany()
                        .HasForeignKey("SetlersSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreWebApiJewelleryProject.Model.Yuzukler", null)
                        .WithMany()
                        .HasForeignKey("YuzuklersYuzukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
